# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: usawscwsrv0072

- task: CmdLine@2
  displayName: 'Run Tosca CI'
  inputs:
    script: 'C:\\agent\\_work\\Client\\ToscaCIClient.exe -m distributed -t junit -r C:\\agent\\_work\\Client\\test.xml'

